effects:
- name: round_corners
  params:
    angle_threshold: 100
    radius: 40
input_font: /Users/koseiyamamoto/Library/CloudStorage/Dropbox/Downloads/NotoSansCJKjp-Medium.otf
output_font: output_rounded.otf
quality_level: high
variation: null
